{
 "title": "Scheduler dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Scheduled time media",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "scheduled_duration_sum/scheduled_pods_total"
    }
   ]
  },
  {
   "title": "Total scheduled pods",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "scheduled_pods_total" }
   ]
  },
  {
   "title": "Rate scheduled pods",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "scheduled_pods_node", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "scheduled_duration_bucket", "legendFormat": "{{le}}" }
   ]
  }
 ]
}